name: Java CI with Gradle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6.0.2

    - name: Set up JDK
      uses: actions/setup-java@v5.2.0
      with:
        distribution: 'temurin'
        java-version: '21'
 
    - name: Cache Gradle packages
      uses: actions/cache@v5.0.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/configuration-cache
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew :fabric:build :paper:build --no-daemon

    - name: Collect artifacts
      run: |
        mkdir -p artifacts
        cp paper/build/libs/*.jar artifacts/
        cp fabric/build/libs/*.jar artifacts/

    - name: Upload build artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: PlaytimeCommand
        path: artifacts/*.jar